spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
