spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  default-flat-param-object: true

jwt:
  secret: ${JWT_SECRET:local-test-secret-key-1234567890}
  expiration: 1800000
  refresh-expiration: 604800000